### ISSUE TITLE
No Money Button As Of 1.02

### ISSUE THREAD

**Issue by Toonsie** [fiskybusiness/phasmophobia#13]
![image](https://user-images.githubusercontent.com/49470272/95492727-87d48500-0969-11eb-9e4f-8aaef194d840.png)
Cheat is in, working and all but no money button. Using the most recent update as well. Any ideas? Also : I know I asked before but I set the color to #FFFFFF and it's not the default, it's white. Any help would be great!

**Comment by Toonsie** [comment]
Apologies, as of 1.02 as well.

**Comment by fiskybusiness** [comment]
Oh! I'm sorry I must've removed it by mistake... give me a tick

**Comment by fiskybusiness** [comment]
Cheers I've added it back
