### ISSUE TITLE
Big Games and Professional Difficulty distribution

### ISSUE THREAD

**Issue by MistressX** [fiskybusiness/phasmophobia#17]
Hi, i have noticed after update that as a low level i can no longer choose professional difficulty.

I also have one question regarding big games, i have tried hosting about 30 - 40 person game, but it always crashes on 90% load. so far i have tried about 3 times, but it is fine when joining other modded servers with more than 20 people. What these hosted rooms had in common was that they had the maximum player count displayed as zero, "-" sign or there was nothing at all for indicating maximum player count.

**Comment by fiskybusiness** [comment]
Noted on the difficulty.

The crashing is a function both of your computer and other players ability to respond to your requests, Unfortunately the game cannot really handle super large lobbies, especially with multiple ghosts. 

Honestly I've had the best luck with max 16 players or 8 ghosts -- personally I've never tried super large lobbies as they crash often -- especially on asylum

**Comment by MistressX** [comment]
Hi, thank you for the answer, i will try to find what works best, also do you know if there are any game moderators that can kick hosts or remove games?

**Comment by VadamL** [comment]
closed
