### ISSUE TITLE
Modconfig.cfg

### ISSUE THREAD

**Issue by veroinx** [fiskybusiness/phasmophobia#19]
Forgive me, but i haven't been able to figure out how to copy the Modconfig.cfg file into my phasmophobia files. I dont have that file to begin with and it it isn't included with the AssemblyCsharp download. Help me out here :(

Do i just create the file or something?

**Comment by Zombieblowup** [comment]
"Phasmophobia\Phasmophobia_Data\Managed" is where to put both.
Make sure your antivirus or web browser is not deleting it as its downloading. Check your AV first.

**Comment by veroinx** [comment]
I've downloaded the assembly file no problem, but i can't get the config file.  Are they bundled together in the same download?

**Comment by Zombieblowup** [comment]
yes they are: https://github.com/fiskybusiness/phasmophobia/archive/main.zip
