### ISSUE TITLE
Ghost always shows up.

### ISSUE THREAD

**Issue by neon1293** [fiskybusiness/phasmophobia#29]
For some reason the ghost will always show up as a shadow and is visible to the player on every level.
![ghost](https://user-images.githubusercontent.com/65500202/95641647-6a321900-0a58-11eb-8c4a-123323bd9921.png)

**Comment by Zombieblowup** [comment]
what's your config and version are you running? I havent ran into this problem yet. I'll try to recreate.

**Comment by fiskybusiness** [comment]
I added a config for turning the ghosts on. You can turn it off with ghostAlwaysAppear=false

**Comment by neon1293** [comment]
My bad, completely overlooked that option. Solved
