### ISSUE TITLE
Request | Remove the stupid ghost names.

### ISSUE THREAD

**Issue by Crowley1313** [fiskybusiness/phasmophobia#3]
How about removing the absolutely smooth brain retarded ghost names? "Your Mom Gay" and dumb bullshit like that isn't funny, and not because of any SJW bullshit. it's weak lower lip tier "comedy" that only someone who likes RoosterTeeth would enjoy. You should absolutely be ashamed of yourself for creating such a low tier meme.

Remove the bad ghost names, keep the good ghost names. If people want to add shit let them do it, you are a middle man. Your singular job is to make the game more accessible to other people, don't come back here and say something like "Uuuh well I do this on my free time." shut up, will you shut up. You're doing this to get a reputation and your reputation right now is of someone with a severe lack of ripples across their cranium and I promise you that if you don't clean up your act that that reputation will proceed you across all mediums.

**Comment by djseal2038** [comment]
Yes fucking please

**Comment by Reisuz** [comment]
Yeah remove that stupid shit. And maybe make it so if you have more than one ghost it picks different rooms idk if it does this already but i only saw one ghost room.  More inventory slots maybe just up to 4 or put it in the config.

**Comment by desick** [comment]
I like the alternative ghost names. However I recommend doing two things.

1.) Allow us to toggle it on or off
2.) Allow us to add more names to the list. Example: we can add our friend names to it to help create even more caution when calling ghosts.

Also, to the OP, don't be a child.

**Comment by msj1423** [comment]
If you want to return origin ghostnames
Search "possibleMaleFirstNames", cover the following text possibleMaleFirstNames possibleFemaleFirstNames possibleLastNames with the following code.
```
        public string[] possibleMaleFirstNames = new string[]
	{
		"James",
		"John",
		"Robert",
		"Michael",
		"William",
		"David",
		"Richard",
		"Charles",
		"Joseph",
		"Thomas",
		"Christopher",
		"Daniel",
		"Paul",
		"Mark",
		"Donald",
		"George",
		"Kenneth",
		"Steven",
		"Edward",
		"Brian",
		"Ronald",
		"Anthony",
		"Kevin",
		"Jason",
		"Gary",
		"Larry",
		"Eric",
		"Raymond",
		"Jerry",
		"Harold",
		"Pater",
		"Justin",
		"Billy",
		"Carlos",
		"Russell",
		"Walter"
	};
```
```
	public string[] possibleFemaleFirstNames = new string[]
	{
		"Mary",
		"Patricia",
		"Linda",
		"Barbara",
		"Elizabeth",
		"Jennifer",
		"Maria",
		"Susan",
		"Margaret",
		"Dorothy",
		"Lisa",
		"Nancy",
		"Karen",
		"Betty",
		"Helen",
		"Sandra",
		"Donna",
		"Carol",
		"Ruth",
		"Ann",
		"Julie",
		"Doris",
		"Gloria",
		"Judy",
		"Lori",
		"Jane",
		"Ellen",
		"April",
		"Megan",
		"Robin",
		"Holly",
		"Carla",
		"Ella",
		"Stacey",
		"Marcia",
		"Nellie",
		"Shelly"
	};
```
```
	public string[] possibleLastNames = new string[]
	{
		"Smith",
		"Johnson",
		"Williams",
		"Jones",
		"Brown",
		"Miller",
		"Wilson",
		"Moore",
		"Taylor",
		"Anderson",
		"Jackson",
		"White",
		"Harris",
		"Martin",
		"Thompson",
		"Garcia",
		"Martinez",
		"Robinson",
		"Clark",
		"Lewis",
		"Walker",
		"Young",
		"Hill",
		"Hall",
		"Wright",
		"Roberts",
		"Carter",
		"Baker",
		"Wilson",
		"Anderson"
	};
```
Next search "CreateGhost", use the following code to cover the corresponding places
```
if (this.ghostTraits.isMale)
		{
			this.ghostTraits.ghostName = LevelController.instance.possibleMaleFirstNames[UnityEngine.Random.Range(0, LevelController.instance.possibleMaleFirstNames.Length)] + " " + LevelController.instance.possibleLastNames[UnityEngine.Random.Range(0, LevelController.instance.possibleLastNames.Length)];
			prefabName = Constants.maleGhostNames[UnityEngine.Random.Range(0, Constants.maleGhostNames.Length)];
		}
		else
		{
			this.ghostTraits.ghostName = LevelController.instance.possibleFemaleFirstNames[UnityEngine.Random.Range(0, LevelController.instance.possibleFemaleFirstNames.Length)] + " " + LevelController.instance.possibleLastNames[UnityEngine.Random.Range(0, LevelController.instance.possibleLastNames.Length)];
			prefabName = Constants.femaleGhostNames[UnityEngine.Random.Range(0, Constants.femaleGhostNames.Length)];
		}
```
All done.

**Comment by fiskybusiness** [comment]
Adding customization in V1.02. Can also toggle using "useCustomNames" flag
