### ISSUE TITLE
Ghost names.

### ISSUE THREAD

**Issue by DevilSenpaii** [fiskybusiness/phasmophobia#7]
Please change the ghost names, while I thought it was funny at first it kind of becomes annoying after a while, all I'm trying to do is play with 6 people but I keep getting "Your Mom Gay" like 7 games in a row.

**Comment by childxd** [comment]
agreed, allow an option to turn it off please.

**Comment by desick** [comment]
#3 addresses this well. Probably merge.

**Comment by fiskybusiness** [comment]
Adding customization in V1.02. Can also toggle using "useCustomNames" flag
